# Generated by Django 5.2.4 on 2025-08-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_nome_alter_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
